### ISSUE TITLE
Segmentation fault in char_to_cuda

### ISSUE THREAD

**Issue by MaxReimann** [MaxReimann/video-stream-consistency#5]
> this is the backtrace:
> 
> Thread 1 "FlowVideoConsis" received signal SIGSEGV, Segmentation fault.
> 0x00007fffa867df90 in ?? () from /lib/x86_64-linux-gnu/libcuda.so.1
> (gdb) bt
>  0x00007fffa867df90 in  () at /lib/x86_64-linux-gnu/libcuda.so.1
> 0x00007fffa872011a in  () at /lib/x86_64-linux-gnu/libcuda.so.1
> 0x00007fffa8870e3e in  () at /lib/x86_64-linux-gnu/libcuda.so.1
> 00007fffa88729dc in  () at /lib/x86_64-linux-gnu/libcuda.so.1
> 0x00007fffa89cfbb9 in  () at /lib/x86_64-linux-gnu/libcuda.so.1
> 0x00007fffa862e546 in  () at /lib/x86_64-linux-gnu/libcuda.so.1
> 0x00007fffa89aa9a0 in  () at /lib/x86_64-linux-gnu/libcuda.so.1
> 0x00007fffa8628b82 in  () at /lib/x86_64-linux-gnu/libcuda.so.1
> 0x00007fffa87d7c2e in  () at /lib/x86_64-linux-gnu/libcuda.so.1
> 0x00005555556079b1 in libcudart_static_e760a7280bc1af45ef561886abc194823c5edadb ()
> 0x00005555555d3c3a in libcudart_static_901c335edfe2e89188fa6b8fe3e2a2194ad05bff ()
> 0x000055555562f4e9 in cudaMemcpy ()
> 0x0000555555576392 in char_to_cuda_float_image(unsigned char*, unsigned long, GPUImage&) ()
> 0x0000555555575e72 in GPUImage::copyFromQImage(QImage const&) ()
> 0x00005555555845b9 in imageToGPU(QImage const&) ()
> 0x0000555555585a4c in FileStabilizer::loadFrame(int) ()
> 0x000055555558d036 in VideoStabilizer::preloadProcessedFrames() ()
> 0x0000555555585d93 in FileStabilizer::stabilizeAll() ()
> 0x00005555555c9fe2 in main ()
> (gdb)  

 _Originally posted by @aditya-raj0 in [#2](https://github.com/MaxReimann/video-stream-consistency/issues/2#issuecomment-2612932174)_

**Comment by MaxReimann** [comment]
@aditya-raj0 Which cuda version are you running on?

**Comment by aditya-raj0** [comment]
@MaxReimann i am using cuda 12.4

**Comment by aditya-raj0** [comment]
@MaxReimann  and initially i did not have libcudnn.so.9 file i had the 8.9 version.

**Comment by MaxReimann** [comment]
The failure would indicate either some kind of error with your cuda setup or the files which are loaded could be corrupted (unlikely), or some issue related to QImage. Hard to say. 
Please check that the images in originalframes and processframes you are giving to the CLI look ok (not corrupted).

And then, can you provide me with:
- the CMake build cache
- your linux distribution and version
- does running a model with onnxruntime standalone work? to test this, install onnxruntime-gpu with pip [install](https://onnxruntime.ai/docs/get-started/with-python.html,) and [run with a simple model ](https://onnxruntime.ai/docs/api/python/auto_examples/plot_load_and_predict.html#sphx-glr-auto-examples-plot-load-and-predict-py)

**Comment by aditya-raj0** [comment]
@MaxReimann thanks for replying,

i have replicated the problem in a colab notebook, please take a look, this has all the logs.

https://colab.research.google.com/drive/1xJdvz0tViF_xHEmZkX1qSvS6c7D2cLsh?usp=sharing

the input frames and the processed frames are the same(for reconstruction) and the frames are named as 000001.jpg, ...

**Comment by MaxReimann** [comment]
Hi, thank you for providing the colab, this helped a lot. It actually turned out there was a bug for large images not in png format, where a heap pointer got prematurely invalidated (this didn't seem to affect smaller images). Please try if it works after pulling the newest commit.

**Comment by aditya-raj0** [comment]
@MaxReimann please tell me if you need more information.

**Comment by aditya-raj0** [comment]
@MaxReimann 

Thanks for the quick resolution, i tried with higher res videos and its not giving segfaults now.

ANOTHER THING: In the paper demo there is a slider of lambda for the level of improvement in temporal consistency. Is that something that can be passed as a parameter at inference time.

**Comment by MaxReimann** [comment]
Yes that is adjusteable in the GUI (FlowConsistencyPlayer)
